services:
  mysql:
    image: mysql:8.0
    container_name: witch-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/amd64
  redis:
    image: redis:alpine
    container_name: witch-redis
    restart: always
    command: redis-server
    hostname: redis
    ports:
      - '6379:6379'
